# Data exploration

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline # helps to plot graphs in line with code-cells

UsageError: unrecognized arguments: # helps to plot graphs in line with code-cells

### Importing the data

In [41]:
root_URL = 'https://raw.githubusercontent.com/StevenVuong/WDL_2020/master/data/stage1'
Churn_OD_file = 'Churn_OD.txt'
Churn_UsersProfile_file = 'Churn_UsersProfile.txt'

Churn_OD_URL = root_URL +'/'+ Churn_OD_file
Churn_UsersProfile_URL = root_URL +'/'+ Churn_UsersProfile_file

In [42]:
df1 = pd.read_csv(Churn_OD_URL ,delimiter="|",encoding = 'Latin1')
df2 = pd.read_csv(Churn_UsersProfile_URL,delimiter="|",encoding = 'Latin1')

In [43]:
df1.head(10)

  Region_of_Origin  ... Demand_weight
0   R1 - AM Lisboa  ...      0.307323
1   R1 - AM Lisboa  ...      0.069997
2   R1 - AM Lisboa  ...      0.066059
3   R1 - AM Lisboa  ...      0.059847
4   R1 - AM Lisboa  ...      0.052341
5   R1 - AM Lisboa  ...      0.049032
6   R1 - AM Lisboa  ...      0.039779
7   R1 - AM Lisboa  ...      0.038691
8   R1 - AM Lisboa  ...      0.037827
9   R1 - AM Lisboa  ...      0.037800

[10 rows x 8 columns]

In [44]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 8 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Region_of_Origin                             2253 non-null   object
 1   District_of_Origin                           2253 non-null   object
 2   County_of_Origin                             2253 non-null   object
 3   Region_of_Public_Transportation              2253 non-null   object
 4   District_of_Public_Transportation            2253 non-null   object
 5   County_of_Public_Transportation              2253 non-null   object
 6   Dicofre_ParishCode_of_Public_Transportation  2253 non-null   int64
 7   Demand_weight                                2253 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 140.9+ KB

In [45]:
df2.head(10)

  Region_of_Origin  ... Average_BusUsers_per_Day
0   R1 - AM Lisboa  ...               294.194206
1   R1 - AM Lisboa  ...              1081.652817
2   R1 - AM Lisboa  ...               235.836653
3   R1 - AM Lisboa  ...               840.951323
4   R1 - AM Lisboa  ...              1216.148092
5   R1 - AM Lisboa  ...              1148.427051
6   R1 - AM Lisboa  ...               421.940180
7   R1 - AM Lisboa  ...               137.697607
8   R1 - AM Lisboa  ...               617.693161
9   R1 - AM Lisboa  ...               867.481913

[10 rows x 7 columns]