# Data exploration

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### Importing the data

In [3]:
root_URL = 'https://raw.githubusercontent.com/StevenVuong/WDL_2020/master/data/stage1'
Churn_OD_file = 'Churn_OD.txt'
Churn_UsersProfile_file = 'Churn_UsersProfile.txt'

Churn_OD_URL = root_URL +'/'+ Churn_OD_file
Churn_UsersProfile_URL = root_URL +'/'+ Churn_UsersProfile_file

In [4]:
df1 = pd.read_csv(Churn_OD_URL ,delimiter="|",encoding = 'Latin1')
#df2 = pd.read_csv(Churn_UsersProfile_URL,delimiter="|",encoding = 'Latin1')

In [5]:
df1.head(10)

  Region_of_Origin  ... Demand_weight
0   R1 - AM Lisboa  ...      0.307323
1   R1 - AM Lisboa  ...      0.069997
2   R1 - AM Lisboa  ...      0.066059
3   R1 - AM Lisboa  ...      0.059847
4   R1 - AM Lisboa  ...      0.052341
5   R1 - AM Lisboa  ...      0.049032
6   R1 - AM Lisboa  ...      0.039779
7   R1 - AM Lisboa  ...      0.038691
8   R1 - AM Lisboa  ...      0.037827
9   R1 - AM Lisboa  ...      0.037800

[10 rows x 8 columns]

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 8 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Region_of_Origin                             2253 non-null   object
 1   District_of_Origin                           2253 non-null   object
 2   County_of_Origin                             2253 non-null   object
 3   Region_of_Public_Transportation              2253 non-null   object
 4   District_of_Public_Transportation            2253 non-null   object
 5   County_of_Public_Transportation              2253 non-null   object
 6   Dicofre_ParishCode_of_Public_Transportation  2253 non-null   int64
 7   Demand_weight                                2253 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 140.9+ KB

In [7]:
## formatting the column value to be lowercase
df1['District_of_Origin'] = df1['District_of_Origin'].str.lower()
df1['County_of_Origin'] = df1['County_of_Origin'].str.lower()

df1['District_of_Public_Transportation'] = df1['District_of_Public_Transportation'].str.lower()
df1['County_of_Public_Transportation'] = df1['County_of_Public_Transportation'].str.lower()

In [8]:
set1 = set(df1['County_of_Origin'])
set2 = set(df1['County_of_Public_Transportation'])

set3 = set1.difference(set2)
set4 = set2.difference(set1)

 **set3** show the counties that don't have direct route back to

In [9]:
for i in set3:
  print (i)

cascais
palmela
póvoa de varzim
espinho
santa maria da feira
vale de cambra
mafra
moita
são joão da madeira
setúbal
vila franca de xira
alcochete
sesimbra
oliveira de azeméis
montijo
barreiro

 **set4** show the counties that don't have direct route back to,
 but as **set4** is empty we assum that all counties in **set2** have return bus route???

In [10]:
for i in set4:
  print (i)

I want to look for:

*   Number of bus journeys in the same Region and Region to Region 
*   Number of bus journeys from District to District
*   Number of bus journeys from County to County

In [11]:
# i want to know the exact routes avalable
df1["Region_Region"] = df1["Region_of_Origin"] + ' to ' + df1["Region_of_Public_Transportation"]
df1["District_District"] = df1["District_of_Origin"] + ' to ' + df1["District_of_Public_Transportation"]
df1["County_County"] = df1["County_of_Origin"] + ' to ' + df1["County_of_Public_Transportation"]

getting that coords

In [12]:
# 
df1_d1_individual_routes = pd.DataFrame(columns=['Original_routes'])
df1_d1_individual_routes['Original_routes'] = df1["County_County"].unique()
df1_d1_individual_routes.head()

                   Original_routes
0                amadora to lisboa
1               amadora to amadora
2                amadora to oeiras
3                amadora to loures
4              amadora to odivelas
..                             ...
437    vila nova de gaia to loures
438     vila nova de gaia to trofa
439    vila nova de gaia to almada
440  vila nova de gaia to odivelas
441    vila nova de gaia to seixal

[442 rows x 1 columns]

In [13]:
df1_d2_individual_routes = pd.DataFrame(columns=['Artifical_routes'])
temp = pd.DataFrame(columns=['Artifical_routes'])

for County_Origin in set1 :
  for County_Desitnation in set1 :
    i = County_Origin +' to '+ County_Desitnation
    temp  = temp .append({'Artifical_routes': i}, ignore_index=True)

df1_d2_individual_routes['Artifical_routes'] = temp ['Artifical_routes']

In [14]:
df1_d1_individual_routes.info()
df1_d2_individual_routes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Original_routes  442 non-null    object
dtypes: object(1)
memory usage: 3.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artifical_routes  1156 non-null   object
dtypes: object(1)
memory usage: 9.2+ KB

In [15]:
df1_individual_routes = pd.concat([df1_d1_individual_routes, df1_d2_individual_routes], axis=1)
df1_individual_routes

          Original_routes                            Artifical_routes
0       amadora to lisboa                            sintra to sintra
1      amadora to amadora                           sintra to amadora
2       amadora to oeiras                             sintra to moita
3       amadora to loures                            sintra to loures
4     amadora to odivelas                            sintra to seixal
...                   ...                                         ...
1151                  NaN             vila franca de xira to odivelas
1152                  NaN            vila franca de xira to alcochete
1153                  NaN                vila franca de xira to trofa
1154                  NaN               vila franca de xira to oeiras
1155                  NaN  vila franca de xira to vila franca de xira

[1156 rows x 2 columns]

##Accuaring County the coordinates

In [16]:
## we need the geopandas and geopy to get coordinates of the of the County in the data set 
## Geocoding service is built on top of OpenStreetMap data
!pip install geopandas
!pip install geopy

Requirement already satisfied: geopandas in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (3.0.1)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.19)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj>=2.2.0->geopandas) (2020.12.5)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (20.3.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (0.7.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: geopy in /usr/local/lib/python3.7/dist-packages (1.17.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.7/dist-packages (from geopy) (1.50)

In [17]:
#Importing the Nominatim geocoder class 
from geopy.geocoders import Nominatim


## We create 'locator' that holds the Geocoding service, Nominatim will get us the coordinara from  the databas 
locator = Nominatim(user_agent='myGeocoder')
## Then we pass the locator we created to geocode any address, in this example, the Eifel tower address.
location = locator.geocode('Champ de Mars, Paris, France')
print(location)
print('Latitude = {}, Longitude = {}'.format(location.latitude, location.longitude))

Champ de Mars, Rue Saint-Dominique, Quartier du Gros-Caillou, Paris 7e Arrondissement, Paris, Île-de-France, France métropolitaine, 75007, France
Latitude = 48.85614465, Longitude = 2.297820393322227

In [18]:
## creaeting datafram with proper formant to
df3 = pd.DataFrame()
location_points = pd.DataFrame()
df3['address'] = df1['County_of_Origin'] + ',' + df1['District_of_Origin'] + ',Portugal'

In [26]:
#for val in df['address'].unique():
#  print (val)
location_points['address'] = df3['address'].unique()
location_points.head()

                   address  ... altitude
0  amadora,lisboa,Portugal  ...      0.0
1  cascais,lisboa,Portugal  ...      0.0
2   lisboa,lisboa,Portugal  ...      0.0
3   loures,lisboa,Portugal  ...      0.0
4    mafra,lisboa,Portugal  ...      0.0

[5 rows x 6 columns]

In [20]:
from geopy.extra.rate_limiter import RateLimiter

## 1 - We create 'locator' that holds the Geocoding service, Nominatim will get us the coordinara from  the databas 
locator = Nominatim(user_agent='myGeocoder')
## 2 - conveneint function to delay between geocoding calls
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)
## 3 - create location column
location_points['location'] = location_points['address'].apply(geocode)
## 4 - create longitude, laatitude and altitude from location column (returns tuple)
location_points['point'] = location_points['location'].apply(lambda loc: tuple(loc.point) if loc else None)

In [21]:
# 4 - split point column into latitude, longitude and altitude columns
location_points[['latitude', 'longitude', 'altitude']] = pd.DataFrame(location_points['point'].tolist(), index=location_points.index)

In [25]:
location_points.head()

                   address  ... altitude
0  amadora,lisboa,Portugal  ...      0.0
1  cascais,lisboa,Portugal  ...      0.0
2   lisboa,lisboa,Portugal  ...      0.0
3   loures,lisboa,Portugal  ...      0.0
4    mafra,lisboa,Portugal  ...      0.0

[5 rows x 6 columns]